[book]
authors = ["Matteo Di Tucci"]
language = "en"
multilingual = false
src = "src"
title = "A Compendium of Software Design"
description = "A summary with sources of what contributes to good software design"
