name: github-pages

# using https://github.com/peaceiris/actions-mdbook

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with: 
          mdbook-version: '0.4.6'

      - run: mdbook clean && mdbook build && cp ./sitemap.txt ./book/sitemap.txt && cp ./CNAME ./book/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book 
        
        
